// makeus: 1 = kuiva, 2 = puolikuiva, 3 = puolimakea, 4 = makea
var viinit=
    [
        {"nimi":"Matua Sauvignon Blanc 2016 hanapakkaus",
         "kuva":"images/matua-sauvignon-blanc-2016-hanapakkaus.jpg",
         "hinta":22.93,
         "maa":"Uusi-Seelanti",
         "kuvaus":"Kuiva, hapokas, sitruksinen, herukkainen, kevyen yrttinen, hennon mineraalinen",
         "makeus":1,
         "arvio": "Oma EHDOTON suosikkimme, jonka veroista emme ole löytäneet edes Puolan viinitiloilta. Kaikista autenttisin kokemus saadaan juomalla Matua juhannuksena, pahvimukaista. Matua on aidoimmillaan hanapakkauksesta, mutta pullojakin on nykyään saatavilla."
        },
        {"nimi":"Devil's Rock Riesling 2016",
         "kuva":"images/devils-rock-riesling-2016.jpg",
         "hinta":8.69,
         "maa":"Saksa",
         "kuvaus":"Puolikuiva, hapokas, hunajameloninen, aprikoosinen, klementiininen",
         "makeus":2,
         "arvio": "Melko menevä, kiva pippalojuoman, noin hintansa puolesta."
        },
        {"nimi":"St. Ursula Ornament Organic 2016",
         "kuva":"images/ornament.jpg",
         "hinta":8.69,
         "maa":"Saksa",
         "kuvaus": "Puolimakea, keskihapokas, persikkainen, päärynäinen, hennon kukkainen",
         "makeus":3,
         "arvio": "Muuttoviini. Jos muutto on seuraavana päivänä, tämä kannattaa napata Alkon hyllyltä matkaan. Alkaa ne laatikotkin täyttyä kuin itsestään."
        },
        {"nimi":"Bird's Tree 2016",
         "kuva":"images/birds.jpg",
         "hinta":7.39,
         "maa":"Unkari",
         "kuvaus":"Makea, keskihapokas, persikkainen, kypsän päärynäinen, kevyen kukkainen, hennon hunajainen",
         "makeus":4,
         "arvio": "Monien miesten suosikki. Ei liian viinimäinen, kuulemma."
        },
        {"nimi":"Mud House Sauvignon Blanc 2016",
         "kuva":"images/mudhouse.jpg",
         "hinta":14.99,
         "maa":"Uusi-Seelanti",
         "kuvaus":"Kuiva, hapokas, limettinen, viherherukkainen, tomaatinlehtinen, nokkosinen, rodukas",
         "makeus":1,
         "arvio": "Olemme hanakasti etsineet Matuasta korviketta, koska sitä ei ole ollut pulloissa saatavilla. Mud House on Alkon valikoimasta lähimpänä Matuaa. "
        },
        {"nimi":"Pino Pino Vino Frizzante Pinot Noir",
         "kuva":"images/pinopino.jpg",
         "hinta":8.98,
         "maa":"Italia",
         "kuvaus":"Puolikuiva, hapokas, päärynäinen, sitruksinen, kevyen persikkainen. pirskahteleva",
         "makeus":2,
         "arvio": "Tätä onkin todella simppeli juoda! Viinin maku itsessään on mieto, mutta tämä sopii erityisesti tilanteisiin joissa haluaa nopeasti pullon tyhjäksi. "
        },
        {"nimi":"Hardys Bin 141 Colombard Chardonnay 2016",
         "kuva":"images/hardys.jpg",
         "hinta":6.99,
         "maa":"Australia",
         "kuvaus":"Kuiva, hapokas, päärynähilloinen, sitruksinen, viheromenainen, kevyen yrttinen",
         "makeus":1,
         "arvio": "Ei vielä arviota."
        },
        {"nimi":"Douglas Green Chenin Blanc 2017",
         "kuva":"images/douglas.jpg",
         "hinta":6.99,
         "maa":"Etelä-Afrikka",
         "kuvaus":"Kuiva, hapokas, kypsän sitruksinen, klementiininen, viheromenainen, yrttinen",
         "makeus":1,
         "arvio": "Tämä on todella hyvä luomuviini!"
        },
        {"nimi":"Black Tower Classic Riesling 2016",
         "kuva":"images/blacktower.jpg",
         "hinta":9.49,
         "maa":"Saksa",
         "kuvaus":"Puolikuiva, hapokas, sitruksinen, viheromenainen, kevyen aprikoosinen, yrttinen",
         "makeus":2,
         "arvio": "Black Towereista kaikki ovat klassikkoviinejä. Usein valintana kiireellisissä päätöksissä, koska tietää saavansa taattua laatua. "
        },
            {"nimi":"Vicarage Lane Marlborough Sauvignon Blanc 2017",
         "kuva":"images/vicarage.jpg",
         "hinta":11.99,
         "maa":"Uusi-Seelanti",
         "kuvaus":"Kuiva, hapokas, limettinen, viherherukkainen, herukanlehtinen, kevyen passionhedelmäinen",
         "makeus":1,
        "arvio": "Tässä on toinen Matuan korvike. Tässä hyvänä puolena on edukas hinta!"
        },
        {"nimi":"Old Coach Road Unoaked Chardonnay 2016",
         "kuva":"images/oldcoach.jpg",
         "hinta":12.82,
         "maa":"Uusi-Seelanti",
         "kuvaus":"Kuiva, hapokas, kypsän sitruksinen, keltaomenainen, kevyen ananaksinen, mausteinen",
         "makeus":1,
         "arvio": "Kohtuuhyvä viinivalinta kesäisiin illanistujaisiin."
        },
        {"nimi":"Gazzera Pinot Grigio Moscato Organic 2016",
         "kuva":"images/gazzera.jpg",
         "hinta":8.99,
         "maa":"Italia",
         "kuvaus":"Puolikuiva, keskihapokas, sitruksinen, päärynäinen, litsiluumuinen, kukkainen",
         "makeus":2,
         "arvio": "Gazzerra ei säväyttänyt ensimmäisellä lasillisella, mutta kun viinin antoi hieman hengittää, alkoi makukin parantua. Sopii erityisesti glögin kanssa sekoitettuna. "
        },
        {"nimi":"Yellow Tail Pinot Grigio 2016",
         "kuva":"images/yellowtail.jpg",
         "hinta":9.99,
         "maa":"Australia",
         "kuvaus":"Puolikuiva, keskihapokas, sitruksinen, päärynäinen, kevyen persikkainen, yrttinen",
         "makeus":2,
         "arvio": "Ei vielä arviota."
        },
        {"nimi":"Casa di Malia Organic Prosecco Frizzante",
         "kuva":"images/casadi.jpg",
         "hinta":12.49,
         "maa":"Italia",
         "kuvaus":"Puolikuiva, hapokas, pirskahteleva, kevyen limettinen, viherpäärynäinen, hennon aprikoosinen, yrttinen",
         "makeus":2,
         "arvio": "Ei vielä arviota."
        },
        {"nimi":"Asio Otus Bianco",
         "kuva":"images/asio.jpg",
         "hinta":10.98,
         "maa":"Italia",
         "kuvaus":"Puolikuiva, keskihapokas, aprikoosinen, hunajameloninen, sitrushilloinen, kukkainen, mausteinen",
         "makeus":2,
         "arvio": "Ei vielä arviota."
        },
        {"nimi":"Vinha do Rosario 2015",
         "kuva":"images/vinha.jpg",
         "hinta":6.89,
         "maa":"Portugali",
         "kuvaus":"Puolikuiva, keskihapokas, hunajameloninen, päärynäinen, hennon mausteinen",
         "makeus":2,
         "arvio": "Ei vielä arviota."
        },
        {"nimi":"J.P. Chenet Sauvignon Blanc 2016",
         "kuva":"images/jp.jpg",
         "hinta":7.98,
         "maa":"Ranska",
         "kuvaus":"Kuiva, hapokas, karviaismainen, limettinen, kevyen herukkainen, hennon yrttinen",
         "makeus":1,
         "arvio": "Ei vielä arviota."
        },
        {"nimi":"Bigi Est! Est!! Est!!! 2015",
         "kuva":"images/bigi.jpg",
         "hinta":9.01,
         "maa":"Italia",
         "kuvaus":"Kuiva, keskihapokas, sitruksinen, kevyen hedelmäinen, hennon mausteinen",
         "makeus":1,
         "arvio": "Ei vielä arviota."
        },
        {"nimi":"Lamberti Pinot Grigio 2016",
         "kuva":"images/lamberti.jpg",
         "hinta":9.99,
         "maa":"Italia",
         "kuvaus":"Kuiva, keskihapokas, sitruksinen, kypsän päärynäinen, hennon hunajameloninen, kevyen yrttinen",
         "makeus":1,
         "arvio": "Ei vielä arviota."
        },
        {"nimi":"Oodi Vapaudelle Chenin Blanc 2016",
         "kuva":"images/oodi.jpg",
         "hinta":9.99,
         "maa":"Etelä-Afrikka",
         "kuvaus":"Kuiva, hapokas, sitruksinen, viheromenainen, kevyen yrttinen",
         "makeus":1,
         "arvio": "Ei vielä arviota."
        },
        {"nimi":"Jacob's Creek Riesling 2017",
         "kuva":"images/jacobs.jpg",
         "hinta":9.99,
         "maa":"Australia",
         "kuvaus":"Kuiva, hapokas, limettinen, viheromenainen, suolaheinäinen, hennon mineraalinen",
         "makeus":1,
         "arvio": "Ei vielä arviota."
        },
            {"nimi":"Pelicans Sauvignon Blanc 2015",
         "kuva":"images/pelicans.jpg",
         "hinta":10.95,
         "maa":"Chile",
         "kuvaus":"Kuiva, hapokas, yrttinen, sitruksinen, hedelmäinen, aromikas",
         "makeus":1,
        "arvio": "Ei vielä arviota."
        },
        {"nimi":"Kärppäviini",
         "kuva":"images/karppa.jpg",
         "hinta":11.90,
         "maa":"Ranska",
         "kuvaus":"Kuiva, keskihapokas, hedelmäinen",
         "makeus":1,
         "arvio": "Ei vielä arviota."
        },
        {"nimi":"B.io Catarratto Chardonnay Vino Biologico 2016",
         "kuva":"images/bio.jpg",
         "hinta":12.79,
         "maa":"Italia",
         "kuvaus":"Kuiva, keskihapokas, hedelmäinen, sitruksinen, yrttinen",
         "makeus":1,
         "arvio": "Erityisen ihastuttava pullo, ja viini erinomaista. Helppo juoda, mutta maukas!"
         
        },
        {"nimi":"Gatão",
         "kuva":"images/gatao.jpg",
         "hinta":8.19,
         "maa":"Portugali",
         "kuvaus":"Puolikuiva, keskihapokas, viherpäärynäinen, ananaksinen, pirskahteleva.",
         "makeus":2,
         "arvio": "Ei vielä arviota."
        },
        
        {"nimi":"Viña Maipo Moscato",
         "kuva":"images/vina.jpg",
         "hinta":6.99,
         "maa":"Chile",
         "kuvaus":"Makea, keskihapokas, sitruksinen, persikkainen, kevyen päärynäinen, kukkainen",
         "makeus":4,
         "arvio": "Ei vielä arviota."
        }
    ]
    