// makeus: 1 = kuiva, 2 = puolikuiva, 3 = puolimakea, 4 = makea
var viinit=
    [
        {"nimi":"Matua Sauvignon Blanc 2016 hanapakkaus",
         "kuva":"../images/matua-sauvignon-blanc-2016-hanapakkaus.jpg",
         "hinta":"22,93 euroa",
         "maa":"Uusi-Seelanti",
         "kuvaus":"Kuiva, hapokas, sitruksinen, herukkainen, kevyen yrttinen, hennon mineraalinen",
         "makeus":1
        },
        {"nimi":"Devil's Rock Riesling 2016",
         "kuva":"../images/devils-rock-riesling-2016.jpg",
         "hinta":"8,69 euroa",
         "maa":"Saksa",
         "kuvaus":"Puolikuiva, hapokas, hunajameloninen, aprikoosinen, klementiininen",
         "makeus":2
        },
        {"nimi":"St. Ursula Ornament Organic 2016",
         "kuva":"",
         "hinta":"8,69 euroa",
         "maa":"Saksa",
         "kuvaus": "Puolimakea, keskihapokas, persikkainen, päärynäinen, hennon kukkainen",
         "makeus":3
        },
        {"nimi":"Bird's Tree 2016",
         "kuva":"",
         "hinta":"7,39 euroa",
         "maa":"Unkari",
         "kuvaus":"Makea, keskihapokas, persikkainen, kypsän päärynäinen, kevyen kukkainen, hennon hunajainen",
         "makeus":4
        },
        {"nimi":"Mud House Sauvignon Blanc 2016",
         "kuva":"",
         "hinta":"14,99 euroa",
         "maa":"Uusi-Seelanti",
         "kuvaus":"Kuiva, hapokas, limettinen, viherherukkainen, tomaatinlehtinen, nokkosinen, rodukas",
         "makeus":1
        },
        {"nimi":"Pino Pino Vino Frizzante Pinot Noir",
         "kuva":"",
         "hinta":"8,98 euroa",
         "maa":"Italia",
         "kuvaus":"Puolikuiva, hapokas, päärynäinen, sitruksinen, kevyen persikkainen. pirskahteleva",
         "makeus":2
        },
        {"nimi":"Hardys Bin 141 Colombard Chardonnay 2016",
         "kuva":"",
         "hinta":"6,99 euroa",
         "maa":"Australia",
         "kuvaus":"Kuiva, hapokas, päärynähilloinen, sitruksinen, viheromenainen, kevyen yrttinen",
         "makeus":1
        },
        {"nimi":"Douglas Green Chenin Blanc 2017",
         "kuva":"",
         "hinta":"6,99 euroa",
         "maa":"Etelä-Afrikka",
         "kuvaus":"Kuiva, hapokas, kypsän sitruksinen, klementiininen, viheromenainen, yrttinen",
         "makeus":1
        },
        {"nimi":"Black Tower Classic Riesling 2016",
         "kuva":"",
         "hinta":"9,49 euroa",
         "maa":"Saksa",
         "kuvaus":"Puolikuiva, hapokas, sitruksinen, viheromenainen, kevyen aprikoosinen, yrttinen",
         "makeus":2
        },
            {"nimi":"Vicarage Lane Marlborough Sauvignon Blanc 2017",
         "kuva":"",
         "hinta":"11,99 euroa",
         "maa":"Uusi-Seelanti",
         "kuvaus":"Kuiva, hapokas, limettinen, viherherukkainen, herukanlehtinen, kevyen passionhedelmäinen",
         "makeus":1
        },
        {"nimi":"Old Coach Road Unoaked Chardonnay 2016",
         "kuva":"",
         "hinta":"12,82 euroa",
         "maa":"Uusi-Seelanti",
         "kuvaus":"Kuiva, hapokas, kypsän sitruksinen, keltaomenainen, kevyen ananaksinen, mausteinen",
         "makeus":1
        },
        {"nimi":"Gazzera Pinot Grigio Moscato Organic 2016",
         "kuva":"",
         "hinta":"8,99 euroa",
         "maa":"Italia",
         "kuvaus":"Puolikuiva, keskihapokas, sitruksinen, päärynäinen, litsiluumuinen, kukkainen",
         "makeus":2
        },
        {"nimi":"Yellow Tail Pinot Grigio 2016",
         "kuva":"",
         "hinta":"9,99 euroa",
         "maa":"Australia",
         "kuvaus":"Puolikuiva, keskihapokas, sitruksinen, päärynäinen, kevyen persikkainen, yrttinen",
         "makeus":2
        },
        {"nimi":"Casa di Malia Organic Prosecco Frizzante",
         "kuva":"",
         "hinta":"12,49 euroa",
         "maa":"Italia",
         "kuvaus":"Puolikuiva, hapokas, pirskahteleva, kevyen limettinen, viherpäärynäinen, hennon aprikoosinen, yrttinen",
         "makeus":2
        },
        {"nimi":"Asio Otus Bianco",
         "kuva":"",
         "hinta":"10,98 euroa",
         "maa":"Italia",
         "kuvaus":"Puolikuiva, keskihapokas, aprikoosinen, hunajameloninen, sitrushilloinen, kukkainen, mausteinen",
         "makeus":2
        },
        {"nimi":"Vinha do Rosario 2015",
         "kuva":"",
         "hinta":"6,89 euroa",
         "maa":"Portugali",
         "kuvaus":"Puolikuiva, keskihapokas, hunajameloninen, päärynäinen, hennon mausteinen",
         "makeus":2
        },
        {"nimi":"J.P. Chenet Sauvignon Blanc 2016",
         "kuva":"",
         "hinta":"7,98 euroa",
         "maa":"Ranska",
         "kuvaus":"Kuiva, hapokas, karviaismainen, limettinen, kevyen herukkainen, hennon yrttinen",
         "makeus":1
        },
        {"nimi":"Bigi Est! Est!! Est!!! 2015",
         "kuva":"",
         "hinta":"9,01 euroa",
         "maa":"Italia",
         "kuvaus":"Kuiva, keskihapokas, sitruksinen, kevyen hedelmäinen, hennon mausteinen",
         "makeus":1
        },
        {"nimi":"Lamberti Pinot Grigio 2016",
         "kuva":"",
         "hinta":"9,99 euroa",
         "maa":"Italia",
         "kuvaus":"Kuiva, keskihapokas, sitruksinen, kypsän päärynäinen, hennon hunajameloninen, kevyen yrttinen",
         "makeus":1
        },
        {"nimi":"Oodi Vapaudelle Chenin Blanc 2016",
         "kuva":"",
         "hinta":"9,99 euroa",
         "maa":"Etelä-Afrikka",
         "kuvaus":"Kuiva, hapokas, sitruksinen, viheromenainen, kevyen yrttinen",
         "makeus":1
        },
        {"nimi":"Jacob's Creek Riesling 2017",
         "kuva":"",
         "hinta":"9,99 euroa",
         "maa":"Australia",
         "kuvaus":"Kuiva, hapokas, limettinen, viheromenainen, suolaheinäinen, hennon mineraalinen",
         "makeus":1
        },
            {"nimi":"Pelicans Sauvignon Blanc 2015",
         "kuva":"",
         "hinta":"10,95 euroa",
         "maa":"Chile",
         "kuvaus":"Kuiva, hapokas, yrttinen, sitruksinen, hedelmäinen, aromikas",
         "makeus":1
        },
        {"nimi":"Kärppäviini",
         "kuva":"",
         "hinta":"11,90 euroa",
         "maa":"Ranska",
         "kuvaus":"Kuiva, keskihapokas, hedelmäinen",
         "makeus":1
        },
        {"nimi":"B.io Catarratto Chardonnay Vino Biologico 2016",
         "kuva":"",
         "hinta":"12,79 euroa",
         "maa":"Italia",
         "kuvaus":"Kuiva, keskihapokas, hedelmäinen, sitruksinen, yrttinen",
         "makeus":1
         
        },
        {"nimi":"Gatão",
         "kuva":"",
         "hinta":"8,19 euroa",
         "maa":"Portugali",
         "kuvaus":"Puolikuiva, keskihapokas, viherpäärynäinen, ananaksinen, pirskahteleva.",
         "makeus":2
        },
        
    ]
    